<a href="https://colab.research.google.com/github/barrosyan/sources/blob/main/eletromagnetism_ring_field.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
K=9e9
Q=2e-6
radius=0.1

In [6]:
observation_point=np.array([0.2,0.3,0])
observation_point

array([0.2, 0.3, 0. ])

In [7]:
theta=np.linspace(0.2*np.pi,1000)
x_ring=radius*np.cos(theta)
y_ring=radius*np.sin(theta)
z_ring=0

In [8]:
x_ring

array([ 0.0809017 , -0.05673685, -0.08373959,  0.05254833,  0.08636797,
       -0.04822834, -0.08878028,  0.0437877 ,  0.09097047, -0.0392375 ,
       -0.09293306,  0.03458914,  0.09466316, -0.02985424, -0.09615642,
        0.02504465,  0.09740911, -0.0201724 , -0.0984181 ,  0.01524968,
        0.09918087, -0.01028881, -0.0996955 ,  0.0053022 ,  0.0999607 ,
       -0.00030233, -0.09997583, -0.0046983 ,  0.09974082,  0.00968718,
       -0.09925629, -0.01465182,  0.09852343,  0.01957981, -0.09754408,
       -0.02445881,  0.09632069,  0.02927661, -0.09485632, -0.03402117,
        0.09315463,  0.03868062, -0.09121989, -0.04324329,  0.08905693,
        0.04769778, -0.08667116, -0.05203293,  0.08406856,  0.05623791])

In [9]:
y_ring

array([ 0.05877853,  0.0823464 , -0.05465969, -0.08508039,  0.0504041 ,
        0.08760152, -0.04602242, -0.08990349,  0.04152559,  0.09198053,
       -0.03692487, -0.09382746,  0.03223177,  0.09543964, -0.02745803,
       -0.09681305,  0.02261559,  0.09794424, -0.01771658, -0.0988304 ,
        0.01277324,  0.09946929, -0.00779795, -0.09985933,  0.00280314,
        0.09999954,  0.00219868, -0.09988957, -0.00719499,  0.09952969,
        0.01217331, -0.0989208 , -0.01712117,  0.09806442,  0.0220262 ,
       -0.09696271, -0.02687612,  0.09561841,  0.0316588 , -0.09403489,
       -0.03636227,  0.0922161 ,  0.04097477, -0.09016661, -0.04548476,
        0.08789153,  0.04988096, -0.08539657, -0.05415236,  0.08268795])

In [14]:
electric_field=np.zeros(3)
electric_field

array([0., 0., 0.])

In [15]:
for i in range(len(theta)):
  r=observation_point-np.array((x_ring[i],y_ring[i],z_ring))
  r_mag=np.linalg.norm(r)
  electric_field+=(K*Q/r_mag**3)*r

In [16]:
print(f"Electric Field at Observation Point: {electric_field}")

Electric Field at Observation Point: [4132635.38337162 6200684.5014172        0.        ]
